#List the players in here that are allowed to use the plugins commands! (separate with ',')
allowed-players: ""

#Players who wont get the "onJoin" message (separate with ",")
blacklist-join-msg: ""

#reports (please do not mess with! Plugin will automatically remove and add the values stored here!)

reports:
  total: